server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

keycloak:
  realm: codeflix
  host: http://localhost:8443

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:3307